-- 다음과 같은 순으로 INSERT되어야 ID(FK)값 참조하지 못하는 상황을 방지할 수 있다 MEMBER -> ARTICLE -> MAIN_BLOCK -> SUB_BLOCK
INSERT INTO MEMBER (EMAIL, NAME, PWD) VALUES ('guest@gmail.com', '게스트', 'guestPwd');

INSERT INTO ARTICLE (DATE_TIME, TITLE, MEMBER_ID, SEQUENCE) VALUES ('2019-09-19 12:34:56', '토비의 스프링 리뷰', 1, 5);

INSERT INTO MAIN_BLOCK (NEXT_POINTER, PREV_POINTER, SEQUENCE_ID, ARTICLE_ID) VALUES (2, null, 1, 1);
-- INSERT INTO MAIN_BLOCK (NEXT_POINTER, PREV_POINTER, SEQUENCE_ID, ARTICLE_ID) VALUES (null, 1, 2, 1);

INSERT INTO SUB_BLOCK (PREV_POINTER, NEXT_POINTER, SEQUENCE_ID, CAN_SHARE, CATEGORY, CONTENT, END, START, MAIN_BLOCK_ID) VALUES (null, 3, 2, true, 'OBSERVATION', '스프링은 프레임워크다. 프레임워크는 개발자의 코드가 이미 만들어진 코드에 편승되어 동작하게 한다', 1, 2, 1);
INSERT INTO SUB_BLOCK (PREV_POINTER, NEXT_POINTER, SEQUENCE_ID, CAN_SHARE, CATEGORY, CONTENT, END, START, MAIN_BLOCK_ID) VALUES (2, 4, 3, true, 'INTERPRETATION', '라이브러리와의 차이점을 명확하게 깨달았다.', 1, 2, 1);
INSERT INTO SUB_BLOCK (PREV_POINTER, NEXT_POINTER, SEQUENCE_ID, CAN_SHARE, CATEGORY, CONTENT, END, START, MAIN_BLOCK_ID) VALUES (3, null, 4, true, 'APPLICATION', '프레임워크와 라이브러리의 차이를 다이어그램으로 표현해보기', 1, 2, 1);

-- INSERT INTO SUB_BLOCK (PREV_POINTER, NEXT_POINTER, SEQUENCE_ID, CAN_SHARE, CATEGORY, CONTENT, END, START, MAIN_BLOCK_ID) VALUES (null, null, 1, true, 'OBSERVATION', '스프링은 자바 엔터프라이즈 애플리케이션 개발에 도움이 되는 프레임워크다', 3, 4, 2);
